<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class UpazilaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $upazilas = array(
            array('id' => '1','district_id' => '1','name' => 'Debidwar'),
            array('id' => '2','district_id' => '1','name' => 'Barura'),
            array('id' => '3','district_id' => '1','name' => 'Brahmanpara'),
            array('id' => '4','district_id' => '1','name' => 'Chandina'),
            array('id' => '5','district_id' => '1','name' => 'Chauddagram'),
            array('id' => '6','district_id' => '1','name' => 'Daudkandi'),
            array('id' => '7','district_id' => '1','name' => 'Homna'),
            array('id' => '8','district_id' => '1','name' => 'Laksam'),
            array('id' => '9','district_id' => '1','name' => 'Muradnagar'),
            array('id' => '10','district_id' => '1','name' => 'Nangalkot'),
            array('id' => '11','district_id' => '1','name' => 'Comilla Sadar'),
            array('id' => '12','district_id' => '1','name' => 'Meghna'),
            array('id' => '13','district_id' => '1','name' => 'Monohargonj'),
            array('id' => '14','district_id' => '1','name' => 'Sadarsouth'),
            array('id' => '15','district_id' => '1','name' => 'Titas'),
            array('id' => '16','district_id' => '1','name' => 'Burichang'),
            array('id' => '17','district_id' => '1','name' => 'Lalmai'),
            array('id' => '18','district_id' => '2','name' => 'Chhagalnaiya'),
            array('id' => '19','district_id' => '2','name' => 'Feni Sadar'),
            array('id' => '20','district_id' => '2','name' => 'Sonagazi'),
            array('id' => '21','district_id' => '2','name' => 'Fulgazi'),
            array('id' => '22','district_id' => '2','name' => 'Parshuram'),
            array('id' => '23','district_id' => '2','name' => 'Daganbhuiyan'),
            array('id' => '24','district_id' => '3','name' => 'Brahmanbaria Sadar'),
            array('id' => '25','district_id' => '3','name' => 'Kasba'),
            array('id' => '26','district_id' => '3','name' => 'Nasirnagar'),
            array('id' => '27','district_id' => '3','name' => 'Sarail'),
            array('id' => '28','district_id' => '3','name' => 'Ashuganj'),
            array('id' => '29','district_id' => '3','name' => 'Akhaura'),
            array('id' => '30','district_id' => '3','name' => 'Nabinagar'),
            array('id' => '31','district_id' => '3','name' => 'Bancharampur'),
            array('id' => '32','district_id' => '3','name' => 'Bijoynagar'),
            array('id' => '33','district_id' => '4','name' => 'Rangamati Sadar'),
            array('id' => '34','district_id' => '4','name' => 'Kaptai'),
            array('id' => '35','district_id' => '4','name' => 'Kawkhali'),
            array('id' => '36','district_id' => '4','name' => 'Baghaichari'),
            array('id' => '37','district_id' => '4','name' => 'Barkal'),
            array('id' => '38','district_id' => '4','name' => 'Langadu'),
            array('id' => '39','district_id' => '4','name' => 'Rajasthali'),
            array('id' => '40','district_id' => '4','name' => 'Belaichari'),
            array('id' => '41','district_id' => '4','name' => 'Juraichari'),
            array('id' => '42','district_id' => '4','name' => 'Naniarchar'),
            array('id' => '43','district_id' => '5','name' => 'Noakhali Sadar'),
            array('id' => '44','district_id' => '5','name' => 'Companiganj'),
            array('id' => '45','district_id' => '5','name' => 'Begumganj'),
            array('id' => '46','district_id' => '5','name' => 'Hatia'),
            array('id' => '47','district_id' => '5','name' => 'Subarnachar'),
            array('id' => '48','district_id' => '5','name' => 'Kabirhat'),
            array('id' => '49','district_id' => '5','name' => 'Senbug'),
            array('id' => '50','district_id' => '5','name' => 'Chatkhil'),
            array('id' => '51','district_id' => '5','name' => 'Sonaimori'),
            array('id' => '52','district_id' => '6','name' => 'Haimchar'),
            array('id' => '53','district_id' => '6','name' => 'Kachua'),
            array('id' => '54','district_id' => '6','name' => 'Shahrasti'),
            array('id' => '55','district_id' => '6','name' => 'Chandpur Sadar'),
            array('id' => '56','district_id' => '6','name' => 'Matlab South'),
            array('id' => '57','district_id' => '6','name' => 'Hajiganj'),
            array('id' => '58','district_id' => '6','name' => 'Matlab North'),
            array('id' => '59','district_id' => '6','name' => 'Faridgonj'),
            array('id' => '60','district_id' => '7','name' => 'Lakshmipur Sadar'),
            array('id' => '61','district_id' => '7','name' => 'Kamalnagar'),
            array('id' => '62','district_id' => '7','name' => 'Raipur'),
            array('id' => '63','district_id' => '7','name' => 'Ramgati'),
            array('id' => '64','district_id' => '7','name' => 'Ramganj'),
            array('id' => '65','district_id' => '8','name' => 'Rangunia'),
            array('id' => '66','district_id' => '8','name' => 'Sitakunda'),
            array('id' => '67','district_id' => '8','name' => 'Mirsharai'),
            array('id' => '68','district_id' => '8','name' => 'Patiya'),
            array('id' => '69','district_id' => '8','name' => 'Sandwip'),
            array('id' => '70','district_id' => '8','name' => 'Banshkhali'),
            array('id' => '71','district_id' => '8','name' => 'Boalkhali'),
            array('id' => '72','district_id' => '8','name' => 'Anwara'),
            array('id' => '73','district_id' => '8','name' => 'Chandanaish'),
            array('id' => '74','district_id' => '8','name' => 'Satkania'),
            array('id' => '75','district_id' => '8','name' => 'Lohagara'),
            array('id' => '76','district_id' => '8','name' => 'Hathazari'),
            array('id' => '77','district_id' => '8','name' => 'Fatikchhari'),
            array('id' => '78','district_id' => '8','name' => 'Raozan'),
            array('id' => '79','district_id' => '8','name' => 'Karnafuli'),
            array('id' => '80','district_id' => '9','name' => 'Coxsbazar Sadar'),
            array('id' => '81','district_id' => '9','name' => 'Chakaria'),
            array('id' => '82','district_id' => '9','name' => 'Kutubdia'),
            array('id' => '83','district_id' => '9','name' => 'Ukhiya'),
            array('id' => '84','district_id' => '9','name' => 'Moheshkhali'),
            array('id' => '85','district_id' => '9','name' => 'Pekua'),
            array('id' => '86','district_id' => '9','name' => 'Ramu'),
            array('id' => '87','district_id' => '9','name' => 'Teknaf'),
            array('id' => '88','district_id' => '10','name' => 'Khagrachhari Sadar'),
            array('id' => '89','district_id' => '10','name' => 'Dighinala'),
            array('id' => '90','district_id' => '10','name' => 'Panchari'),
            array('id' => '91','district_id' => '10','name' => 'Laxmichhari'),
            array('id' => '92','district_id' => '10','name' => 'Mohalchari'),
            array('id' => '93','district_id' => '10','name' => 'Manikchari'),
            array('id' => '94','district_id' => '10','name' => 'Ramgarh'),
            array('id' => '95','district_id' => '10','name' => 'Matiranga'),
            array('id' => '96','district_id' => '10','name' => 'Guimara'),
            array('id' => '97','district_id' => '11','name' => 'Bandarban Sadar'),
            array('id' => '98','district_id' => '11','name' => 'Alikadam'),
            array('id' => '99','district_id' => '11','name' => 'Naikhongchhari'),
            array('id' => '100','district_id' => '11','name' => 'Rowangchhari'),
            array('id' => '101','district_id' => '11','name' => 'Lama'),
            array('id' => '102','district_id' => '11','name' => 'Ruma'),
            array('id' => '103','district_id' => '11','name' => 'Thanchi'),
            array('id' => '104','district_id' => '12','name' => 'Belkuchi'),
            array('id' => '105','district_id' => '12','name' => 'Chauhali'),
            array('id' => '106','district_id' => '12','name' => 'Kamarkhand'),
            array('id' => '107','district_id' => '12','name' => 'Kazipur'),
            array('id' => '108','district_id' => '12','name' => 'Raigonj'),
            array('id' => '109','district_id' => '12','name' => 'Shahjadpur'),
            array('id' => '110','district_id' => '12','name' => 'Sirajganj Sadar'),
            array('id' => '111','district_id' => '12','name' => 'Tarash'),
            array('id' => '112','district_id' => '12','name' => 'Ullapara'),
            array('id' => '113','district_id' => '13','name' => 'Sujanagar'),
            array('id' => '114','district_id' => '13','name' => 'Ishurdi'),
            array('id' => '115','district_id' => '13','name' => 'Bhangura'),
            array('id' => '116','district_id' => '13','name' => 'Pabna Sadar'),
            array('id' => '117','district_id' => '13','name' => 'Bera'),
            array('id' => '118','district_id' => '13','name' => 'Atghoria'),
            array('id' => '119','district_id' => '13','name' => 'Chatmohar'),
            array('id' => '120','district_id' => '13','name' => 'Santhia'),
            array('id' => '121','district_id' => '13','name' => 'Faridpur'),
            array('id' => '122','district_id' => '14','name' => 'Kahaloo'),
            array('id' => '123','district_id' => '14','name' => 'Bogra Sadar'),
            array('id' => '124','district_id' => '14','name' => 'Shariakandi'),
            array('id' => '125','district_id' => '14','name' => 'Shajahanpur'),
            array('id' => '126','district_id' => '14','name' => 'Dupchanchia'),
            array('id' => '127','district_id' => '14','name' => 'Adamdighi'),
            array('id' => '128','district_id' => '14','name' => 'Nondigram'),
            array('id' => '129','district_id' => '14','name' => 'Sonatala'),
            array('id' => '130','district_id' => '14','name' => 'Dhunot'),
            array('id' => '131','district_id' => '14','name' => 'Gabtali'),
            array('id' => '132','district_id' => '14','name' => 'Sherpur'),
            array('id' => '133','district_id' => '14','name' => 'Shibganj'),
            array('id' => '134','district_id' => '15','name' => 'Paba'),
            array('id' => '135','district_id' => '15','name' => 'Durgapur'),
            array('id' => '136','district_id' => '15','name' => 'Mohonpur'),
            array('id' => '137','district_id' => '15','name' => 'Charghat'),
            array('id' => '138','district_id' => '15','name' => 'Puthia'),
            array('id' => '139','district_id' => '15','name' => 'Bagha'),
            array('id' => '140','district_id' => '15','name' => 'Godagari'),
            array('id' => '141','district_id' => '15','name' => 'Tanore'),
            array('id' => '142','district_id' => '15','name' => 'Bagmara'),
            array('id' => '143','district_id' => '16','name' => 'Natore Sadar'),
            array('id' => '144','district_id' => '16','name' => 'Singra'),
            array('id' => '145','district_id' => '16','name' => 'Baraigram'),
            array('id' => '146','district_id' => '16','name' => 'Bagatipara'),
            array('id' => '147','district_id' => '16','name' => 'Lalpur'),
            array('id' => '148','district_id' => '16','name' => 'Gurudaspur'),
            array('id' => '149','district_id' => '16','name' => 'Naldanga'),
            array('id' => '150','district_id' => '17','name' => 'Akkelpur'),
            array('id' => '151','district_id' => '17','name' => 'Kalai'),
            array('id' => '152','district_id' => '17','name' => 'Khetlal'),
            array('id' => '153','district_id' => '17','name' => 'Panchbibi'),
            array('id' => '154','district_id' => '17','name' => 'Joypurhat Sadar'),
            array('id' => '155','district_id' => '18','name' => 'Chapainawabganj Sadar'),
            array('id' => '156','district_id' => '18','name' => 'Gomostapur'),
            array('id' => '157','district_id' => '18','name' => 'Nachol'),
            array('id' => '158','district_id' => '18','name' => 'Bholahat'),
            array('id' => '159','district_id' => '18','name' => 'Shibganj'),
            array('id' => '160','district_id' => '19','name' => 'Mohadevpur'),
            array('id' => '161','district_id' => '19','name' => 'Badalgachi'),
            array('id' => '162','district_id' => '19','name' => 'Patnitala'),
            array('id' => '163','district_id' => '19','name' => 'Dhamoirhat'),
            array('id' => '164','district_id' => '19','name' => 'Niamatpur'),
            array('id' => '165','district_id' => '19','name' => 'Manda'),
            array('id' => '166','district_id' => '19','name' => 'Atrai'),
            array('id' => '167','district_id' => '19','name' => 'Raninagar'),
            array('id' => '168','district_id' => '19','name' => 'Naogaon Sadar'),
            array('id' => '169','district_id' => '19','name' => 'Porsha'),
            array('id' => '170','district_id' => '19','name' => 'Sapahar'),
            array('id' => '171','district_id' => '20','name' => 'Manirampur'),
            array('id' => '172','district_id' => '20','name' => 'Abhaynagar'),
            array('id' => '173','district_id' => '20','name' => 'Bagherpara'),
            array('id' => '174','district_id' => '20','name' => 'Chougachha'),
            array('id' => '175','district_id' => '20','name' => 'Jhikargacha'),
            array('id' => '176','district_id' => '20','name' => 'Keshabpur'),
            array('id' => '177','district_id' => '20','name' => 'Jessore Sadar'),
            array('id' => '178','district_id' => '20','name' => 'Sharsha'),
            array('id' => '179','district_id' => '21','name' => 'Assasuni'),
            array('id' => '180','district_id' => '21','name' => 'Debhata'),
            array('id' => '181','district_id' => '21','name' => 'Kalaroa'),
            array('id' => '182','district_id' => '21','name' => 'Satkhira Sadar'),
            array('id' => '183','district_id' => '21','name' => 'Shyamnagar'),
            array('id' => '184','district_id' => '21','name' => 'Tala'),
            array('id' => '185','district_id' => '21','name' => 'Kaliganj'),
            array('id' => '186','district_id' => '22','name' => 'Mujibnagar'),
            array('id' => '187','district_id' => '22','name' => 'Meherpur Sadar'),
            array('id' => '188','district_id' => '22','name' => 'Gangni'),
            array('id' => '189','district_id' => '23','name' => 'Narail Sadar'),
            array('id' => '190','district_id' => '23','name' => 'Lohagara'),
            array('id' => '191','district_id' => '23','name' => 'Kalia'),
            array('id' => '192','district_id' => '24','name' => 'Chuadanga Sadar'),
            array('id' => '193','district_id' => '24','name' => 'Alamdanga'),
            array('id' => '194','district_id' => '24','name' => 'Damurhuda'),
            array('id' => '195','district_id' => '24','name' => 'Jibannagar'),
            array('id' => '196','district_id' => '25','name' => 'Kushtia Sadar'),
            array('id' => '197','district_id' => '25','name' => 'Kumarkhali'),
            array('id' => '198','district_id' => '25','name' => 'Khoksa'),
            array('id' => '199','district_id' => '25','name' => 'Mirpur'),
            array('id' => '200','district_id' => '25','name' => 'Daulatpur'),
            array('id' => '201','district_id' => '25','name' => 'Bheramara'),
            array('id' => '202','district_id' => '26','name' => 'Shalikha'),
            array('id' => '203','district_id' => '26','name' => 'Sreepur'),
            array('id' => '204','district_id' => '26','name' => 'Magura Sadar'),
            array('id' => '205','district_id' => '26','name' => 'Mohammadpur'),
            array('id' => '206','district_id' => '27','name' => 'Paikgasa'),
            array('id' => '207','district_id' => '27','name' => 'Fultola'),
            array('id' => '208','district_id' => '27','name' => 'Digholia'),
            array('id' => '209','district_id' => '27','name' => 'Rupsha'),
            array('id' => '210','district_id' => '27','name' => 'Terokhada'),
            array('id' => '211','district_id' => '27','name' => 'Dumuria'),
            array('id' => '212','district_id' => '27','name' => 'Botiaghata'),
            array('id' => '213','district_id' => '27','name' => 'Dakop'),
            array('id' => '214','district_id' => '27','name' => 'Koyra'),
            array('id' => '215','district_id' => '28','name' => 'Fakirhat'),
            array('id' => '216','district_id' => '28','name' => 'Bagerhat Sadar'),
            array('id' => '217','district_id' => '28','name' => 'Mollahat'),
            array('id' => '218','district_id' => '28','name' => 'Sarankhola'),
            array('id' => '219','district_id' => '28','name' => 'Rampal'),
            array('id' => '220','district_id' => '28','name' => 'Morrelganj'),
            array('id' => '221','district_id' => '28','name' => 'Kachua'),
            array('id' => '222','district_id' => '28','name' => 'Mongla'),
            array('id' => '223','district_id' => '28','name' => 'Chitalmari'),
            array('id' => '224','district_id' => '29','name' => 'Jhenaidah Sadar'),
            array('id' => '225','district_id' => '29','name' => 'Shailkupa'),
            array('id' => '226','district_id' => '29','name' => 'Harinakundu'),
            array('id' => '227','district_id' => '29','name' => 'Kaliganj'),
            array('id' => '228','district_id' => '29','name' => 'Kotchandpur'),
            array('id' => '229','district_id' => '29','name' => 'Moheshpur'),
            array('id' => '230','district_id' => '30','name' => 'Jhalakathi Sadar'),
            array('id' => '231','district_id' => '30','name' => 'Kathalia'),
            array('id' => '232','district_id' => '30','name' => 'Nalchity'),
            array('id' => '233','district_id' => '30','name' => 'Rajapur'),
            array('id' => '234','district_id' => '31','name' => 'Bauphal'),
            array('id' => '235','district_id' => '31','name' => 'Patuakhali Sadar'),
            array('id' => '236','district_id' => '31','name' => 'Dumki'),
            array('id' => '237','district_id' => '31','name' => 'Dashmina'),
            array('id' => '238','district_id' => '31','name' => 'Kalapara'),
            array('id' => '239','district_id' => '31','name' => 'Mirzaganj'),
            array('id' => '240','district_id' => '31','name' => 'Galachipa'),
            array('id' => '241','district_id' => '31','name' => 'Rangabali'),
            array('id' => '242','district_id' => '32','name' => 'Pirojpur Sadar'),
            array('id' => '243','district_id' => '32','name' => 'Nazirpur'),
            array('id' => '244','district_id' => '32','name' => 'Kawkhali'),
            array('id' => '245','district_id' => '32','name' => 'Zianagar'),
            array('id' => '246','district_id' => '32','name' => 'Bhandaria'),
            array('id' => '247','district_id' => '32','name' => 'Mathbaria'),
            array('id' => '248','district_id' => '32','name' => 'Nesarabad'),
            array('id' => '249','district_id' => '33','name' => 'Barisal Sadar'),
            array('id' => '250','district_id' => '33','name' => 'Bakerganj'),
            array('id' => '251','district_id' => '33','name' => 'Babuganj'),
            array('id' => '252','district_id' => '33','name' => 'Wazirpur'),
            array('id' => '253','district_id' => '33','name' => 'Banaripara'),
            array('id' => '254','district_id' => '33','name' => 'Gournadi'),
            array('id' => '255','district_id' => '33','name' => 'Agailjhara'),
            array('id' => '256','district_id' => '33','name' => 'Mehendiganj'),
            array('id' => '257','district_id' => '33','name' => 'Muladi'),
            array('id' => '258','district_id' => '33','name' => 'Hizla'),
            array('id' => '259','district_id' => '34','name' => 'Bhola Sadar'),
            array('id' => '260','district_id' => '34','name' => 'Borhan Sddin'),
            array('id' => '261','district_id' => '34','name' => 'Charfesson'),
            array('id' => '262','district_id' => '34','name' => 'Doulatkhan'),
            array('id' => '263','district_id' => '34','name' => 'Monpura'),
            array('id' => '264','district_id' => '34','name' => 'Tazumuddin'),
            array('id' => '265','district_id' => '34','name' => 'Lalmohan'),
            array('id' => '266','district_id' => '35','name' => 'Amtali'),
            array('id' => '267','district_id' => '35','name' => 'Barguna Sadar'),
            array('id' => '268','district_id' => '35','name' => 'Betagi'),
            array('id' => '269','district_id' => '35','name' => 'Bamna'),
            array('id' => '270','district_id' => '35','name' => 'Pathorghata'),
            array('id' => '271','district_id' => '35','name' => 'Taltali'),
            array('id' => '272','district_id' => '36','name' => 'Balaganj'),
            array('id' => '273','district_id' => '36','name' => 'Beanibazar'),
            array('id' => '274','district_id' => '36','name' => 'Bishwanath'),
            array('id' => '275','district_id' => '36','name' => 'Companiganj'),
            array('id' => '276','district_id' => '36','name' => 'Fenchuganj'),
            array('id' => '277','district_id' => '36','name' => 'Golapganj'),
            array('id' => '278','district_id' => '36','name' => 'Gowainghat'),
            array('id' => '279','district_id' => '36','name' => 'Jaintiapur'),
            array('id' => '280','district_id' => '36','name' => 'Kanaighat'),
            array('id' => '281','district_id' => '36','name' => 'Sylhet Sadar'),
            array('id' => '282','district_id' => '36','name' => 'Zakiganj'),
            array('id' => '283','district_id' => '36','name' => 'Dakshinsurma'),
            array('id' => '284','district_id' => '36','name' => 'Osmaninagar'),
            array('id' => '285','district_id' => '37','name' => 'Barlekha'),
            array('id' => '286','district_id' => '37','name' => 'Kamolganj'),
            array('id' => '287','district_id' => '37','name' => 'Kulaura'),
            array('id' => '288','district_id' => '37','name' => 'Moulvibazar Sadar'),
            array('id' => '289','district_id' => '37','name' => 'Rajnagar'),
            array('id' => '290','district_id' => '37','name' => 'Sreemangal'),
            array('id' => '291','district_id' => '37','name' => 'Juri'),
            array('id' => '292','district_id' => '38','name' => 'Nabiganj'),
            array('id' => '293','district_id' => '38','name' => 'Bahubal'),
            array('id' => '294','district_id' => '38','name' => 'Ajmiriganj'),
            array('id' => '295','district_id' => '38','name' => 'Baniachong'),
            array('id' => '296','district_id' => '38','name' => 'Lakhai'),
            array('id' => '297','district_id' => '38','name' => 'Chunarughat'),
            array('id' => '298','district_id' => '38','name' => 'Habiganj Sadar'),
            array('id' => '299','district_id' => '38','name' => 'Madhabpur'),
            array('id' => '300','district_id' => '39','name' => 'Sunamganj Sadar'),
            array('id' => '301','district_id' => '39','name' => 'South Sunamganj'),
            array('id' => '302','district_id' => '39','name' => 'Bishwambarpur'),
            array('id' => '303','district_id' => '39','name' => 'Chhatak'),
            array('id' => '304','district_id' => '39','name' => 'Jagannathpur'),
            array('id' => '305','district_id' => '39','name' => 'Dowarabazar'),
            array('id' => '306','district_id' => '39','name' => 'Tahirpur'),
            array('id' => '307','district_id' => '39','name' => 'Dharmapasha'),
            array('id' => '308','district_id' => '39','name' => 'Jamalganj'),
            array('id' => '309','district_id' => '39','name' => 'Shalla'),
            array('id' => '310','district_id' => '39','name' => 'Derai'),
            array('id' => '311','district_id' => '40','name' => 'Belabo'),
            array('id' => '312','district_id' => '40','name' => 'Monohardi'),
            array('id' => '313','district_id' => '40','name' => 'Narsingdi Sadar'),
            array('id' => '314','district_id' => '40','name' => 'Palash'),
            array('id' => '315','district_id' => '40','name' => 'Raipura'),
            array('id' => '316','district_id' => '40','name' => 'Shibpur'),
            array('id' => '317','district_id' => '41','name' => 'Kaliganj'),
            array('id' => '318','district_id' => '41','name' => 'Kaliakair'),
            array('id' => '319','district_id' => '41','name' => 'Kapasia'),
            array('id' => '320','district_id' => '41','name' => 'Gazipur Sadar'),
            array('id' => '321','district_id' => '41','name' => 'Sreepur'),
            array('id' => '322','district_id' => '42','name' => 'Shariatpur Sadar'),
            array('id' => '323','district_id' => '42','name' => 'Naria'),
            array('id' => '324','district_id' => '42','name' => 'Zajira'),
            array('id' => '325','district_id' => '42','name' => 'Gosairhat'),
            array('id' => '326','district_id' => '42','name' => 'Bhedarganj'),
            array('id' => '327','district_id' => '42','name' => 'Damudya'),
            array('id' => '328','district_id' => '43','name' => 'Araihazar'),
            array('id' => '329','district_id' => '43','name' => 'Bandar'),
            array('id' => '330','district_id' => '43','name' => 'Narayanganj Sadar'),
            array('id' => '331','district_id' => '43','name' => 'Rupganj'),
            array('id' => '332','district_id' => '43','name' => 'Sonargaon'),
            array('id' => '333','district_id' => '44','name' => 'Basail'),
            array('id' => '334','district_id' => '44','name' => 'Bhuapur'),
            array('id' => '335','district_id' => '44','name' => 'Delduar'),
            array('id' => '336','district_id' => '44','name' => 'Ghatail'),
            array('id' => '337','district_id' => '44','name' => 'Gopalpur'),
            array('id' => '338','district_id' => '44','name' => 'Madhupur'),
            array('id' => '339','district_id' => '44','name' => 'Mirzapur'),
            array('id' => '340','district_id' => '44','name' => 'Nagarpur'),
            array('id' => '341','district_id' => '44','name' => 'Sakhipur'),
            array('id' => '342','district_id' => '44','name' => 'Tangail Sadar'),
            array('id' => '343','district_id' => '44','name' => 'Kalihati'),
            array('id' => '344','district_id' => '44','name' => 'Dhanbari'),
            array('id' => '345','district_id' => '45','name' => 'Itna'),
            array('id' => '346','district_id' => '45','name' => 'Katiadi'),
            array('id' => '347','district_id' => '45','name' => 'Bhairab'),
            array('id' => '348','district_id' => '45','name' => 'Tarail'),
            array('id' => '349','district_id' => '45','name' => 'Hossainpur'),
            array('id' => '350','district_id' => '45','name' => 'Pakundia'),
            array('id' => '351','district_id' => '45','name' => 'Kuliarchar'),
            array('id' => '352','district_id' => '45','name' => 'Kishoreganj Sadar'),
            array('id' => '353','district_id' => '45','name' => 'Karimgonj'),
            array('id' => '354','district_id' => '45','name' => 'Bajitpur'),
            array('id' => '355','district_id' => '45','name' => 'Austagram'),
            array('id' => '356','district_id' => '45','name' => 'Mithamoin'),
            array('id' => '357','district_id' => '45','name' => 'Nikli'),
            array('id' => '358','district_id' => '46','name' => 'Harirampur'),
            array('id' => '359','district_id' => '46','name' => 'Saturia'),
            array('id' => '360','district_id' => '46','name' => 'Manikganj Sadar'),
            array('id' => '361','district_id' => '46','name' => 'Gior'),
            array('id' => '362','district_id' => '46','name' => 'Shibaloy'),
            array('id' => '363','district_id' => '46','name' => 'Doulatpur'),
            array('id' => '364','district_id' => '46','name' => 'Singiar'),
            array('id' => '365','district_id' => '47','name' => 'Savar'),
            array('id' => '366','district_id' => '47','name' => 'Dhamrai'),
            array('id' => '367','district_id' => '47','name' => 'Keraniganj'),
            array('id' => '368','district_id' => '47','name' => 'Nawabganj'),
            array('id' => '369','district_id' => '47','name' => 'Dohar'),
            array('id' => '370','district_id' => '48','name' => 'Munshiganj Sadar'),
            array('id' => '371','district_id' => '48','name' => 'Sreenagar'),
            array('id' => '372','district_id' => '48','name' => 'Sirajdikhan'),
            array('id' => '373','district_id' => '48','name' => 'Louhajanj'),
            array('id' => '374','district_id' => '48','name' => 'Gajaria'),
            array('id' => '375','district_id' => '48','name' => 'Tongibari'),
            array('id' => '376','district_id' => '49','name' => 'Rajbari Sadar'),
            array('id' => '377','district_id' => '49','name' => 'Goalanda'),
            array('id' => '378','district_id' => '49','name' => 'Pangsa'),
            array('id' => '379','district_id' => '49','name' => 'Baliakandi'),
            array('id' => '380','district_id' => '49','name' => 'Kalukhali'),
            array('id' => '381','district_id' => '50','name' => 'Madaripur Sadar'),
            array('id' => '382','district_id' => '50','name' => 'Shibchar'),
            array('id' => '383','district_id' => '50','name' => 'Kalkini'),
            array('id' => '384','district_id' => '50','name' => 'Rajoir'),
            array('id' => '385','district_id' => '51','name' => 'Gopalganj Sadar'),
            array('id' => '386','district_id' => '51','name' => 'Kashiani'),
            array('id' => '387','district_id' => '51','name' => 'Tungipara'),
            array('id' => '388','district_id' => '51','name' => 'Kotalipara'),
            array('id' => '389','district_id' => '51','name' => 'Muksudpur'),
            array('id' => '390','district_id' => '52','name' => 'Faridpur Sadar'),
            array('id' => '391','district_id' => '52','name' => 'Alfadanga'),
            array('id' => '392','district_id' => '52','name' => 'Boalmari'),
            array('id' => '393','district_id' => '52','name' => 'Sadarpur'),
            array('id' => '394','district_id' => '52','name' => 'Nagarkanda'),
            array('id' => '395','district_id' => '52','name' => 'Bhanga'),
            array('id' => '396','district_id' => '52','name' => 'Charbhadrasan'),
            array('id' => '397','district_id' => '52','name' => 'Madhukhali'),
            array('id' => '398','district_id' => '52','name' => 'Saltha'),
            array('id' => '399','district_id' => '53','name' => 'Panchagarh Sadar'),
            array('id' => '400','district_id' => '53','name' => 'Debiganj'),
            array('id' => '401','district_id' => '53','name' => 'Boda'),
            array('id' => '402','district_id' => '53','name' => 'Atwari'),
            array('id' => '403','district_id' => '53','name' => 'Tetulia'),
            array('id' => '404','district_id' => '54','name' => 'Nawabganj'),
            array('id' => '405','district_id' => '54','name' => 'Birganj'),
            array('id' => '406','district_id' => '54','name' => 'Ghoraghat'),
            array('id' => '407','district_id' => '54','name' => 'Birampur'),
            array('id' => '408','district_id' => '54','name' => 'Parbatipur'),
            array('id' => '409','district_id' => '54','name' => 'Bochaganj'),
            array('id' => '410','district_id' => '54','name' => 'Kaharol'),
            array('id' => '411','district_id' => '54','name' => 'Fulbari'),
            array('id' => '412','district_id' => '54','name' => 'Dinajpur Sadar'),
            array('id' => '413','district_id' => '54','name' => 'Hakimpur'),
            array('id' => '414','district_id' => '54','name' => 'Khansama'),
            array('id' => '415','district_id' => '54','name' => 'Birol'),
            array('id' => '416','district_id' => '54','name' => 'Chirirbandar'),
            array('id' => '417','district_id' => '55','name' => 'Lalmonirhat Sadar'),
            array('id' => '418','district_id' => '55','name' => 'Kaliganj'),
            array('id' => '419','district_id' => '55','name' => 'Hatibandha'),
            array('id' => '420','district_id' => '55','name' => 'Patgram'),
            array('id' => '421','district_id' => '55','name' => 'Aditmari'),
            array('id' => '422','district_id' => '56','name' => 'Syedpur'),
            array('id' => '423','district_id' => '56','name' => 'Domar'),
            array('id' => '424','district_id' => '56','name' => 'Dimla'),
            array('id' => '425','district_id' => '56','name' => 'Jaldhaka'),
            array('id' => '426','district_id' => '56','name' => 'Kishorganj'),
            array('id' => '427','district_id' => '56','name' => 'Nilphamari Sadar'),
            array('id' => '428','district_id' => '57','name' => 'Sadullapur'),
            array('id' => '429','district_id' => '57','name' => 'Gaibandha Sadar'),
            array('id' => '430','district_id' => '57','name' => 'Palashbari'),
            array('id' => '431','district_id' => '57','name' => 'Saghata'),
            array('id' => '432','district_id' => '57','name' => 'Gobindaganj'),
            array('id' => '433','district_id' => '57','name' => 'Sundarganj'),
            array('id' => '434','district_id' => '57','name' => 'Phulchari'),
            array('id' => '435','district_id' => '58','name' => 'Thakurgaon Sadar'),
            array('id' => '436','district_id' => '58','name' => 'Pirganj'),
            array('id' => '437','district_id' => '58','name' => 'Ranisankail'),
            array('id' => '438','district_id' => '58','name' => 'Haripur'),
            array('id' => '439','district_id' => '58','name' => 'Baliadangi'),
            array('id' => '440','district_id' => '59','name' => 'Rangpur Sadar'),
            array('id' => '441','district_id' => '59','name' => 'Gangachara'),
            array('id' => '442','district_id' => '59','name' => 'Taragonj'),
            array('id' => '443','district_id' => '59','name' => 'Badargonj'),
            array('id' => '444','district_id' => '59','name' => 'Mithapukur'),
            array('id' => '445','district_id' => '59','name' => 'Pirgonj'),
            array('id' => '446','district_id' => '59','name' => 'Kaunia'),
            array('id' => '447','district_id' => '59','name' => 'Pirgacha'),
            array('id' => '448','district_id' => '60','name' => 'Kurigram Sadar'),
            array('id' => '449','district_id' => '60','name' => 'Nageshwari'),
            array('id' => '450','district_id' => '60','name' => 'Bhurungamari'),
            array('id' => '451','district_id' => '60','name' => 'Phulbari'),
            array('id' => '452','district_id' => '60','name' => 'Rajarhat'),
            array('id' => '453','district_id' => '60','name' => 'Ulipur'),
            array('id' => '454','district_id' => '60','name' => 'Chilmari'),
            array('id' => '455','district_id' => '60','name' => 'Rowmari'),
            array('id' => '456','district_id' => '60','name' => 'Charrajibpur'),
            array('id' => '457','district_id' => '61','name' => 'Sherpur Sadar'),
            array('id' => '458','district_id' => '61','name' => 'Nalitabari'),
            array('id' => '459','district_id' => '61','name' => 'Sreebordi'),
            array('id' => '460','district_id' => '61','name' => 'Nokla'),
            array('id' => '461','district_id' => '61','name' => 'Jhenaigati'),
            array('id' => '462','district_id' => '62','name' => 'Fulbaria'),
            array('id' => '463','district_id' => '62','name' => 'Trishal'),
            array('id' => '464','district_id' => '62','name' => 'Bhaluka'),
            array('id' => '465','district_id' => '62','name' => 'Muktagacha'),
            array('id' => '466','district_id' => '62','name' => 'Mymensingh Sadar'),
            array('id' => '467','district_id' => '62','name' => 'Dhobaura'),
            array('id' => '468','district_id' => '62','name' => 'Phulpur'),
            array('id' => '469','district_id' => '62','name' => 'Haluaghat'),
            array('id' => '470','district_id' => '62','name' => 'Gouripur'),
            array('id' => '471','district_id' => '62','name' => 'Gafargaon'),
            array('id' => '472','district_id' => '62','name' => 'Iswarganj'),
            array('id' => '473','district_id' => '62','name' => 'Nandail'),
            array('id' => '474','district_id' => '62','name' => 'Tarakanda'),
            array('id' => '475','district_id' => '63','name' => 'Jamalpur Sadar'),
            array('id' => '476','district_id' => '63','name' => 'Melandah'),
            array('id' => '477','district_id' => '63','name' => 'Islampur'),
            array('id' => '478','district_id' => '63','name' => 'Dewangonj'),
            array('id' => '479','district_id' => '63','name' => 'Sarishabari'),
            array('id' => '480','district_id' => '63','name' => 'Madarganj'),
            array('id' => '481','district_id' => '63','name' => 'Bokshiganj'),
            array('id' => '482','district_id' => '64','name' => 'Barhatta'),
            array('id' => '483','district_id' => '64','name' => 'Durgapur'),
            array('id' => '484','district_id' => '64','name' => 'Kendua'),
            array('id' => '485','district_id' => '64','name' => 'Atpara'),
            array('id' => '486','district_id' => '64','name' => 'Madan'),
            array('id' => '487','district_id' => '64','name' => 'Khaliajuri'),
            array('id' => '488','district_id' => '64','name' => 'Kalmakanda'),
            array('id' => '489','district_id' => '64','name' => 'Mohongonj'),
            array('id' => '490','district_id' => '64','name' => 'Purbadhala'),
            array('id' => '491','district_id' => '64','name' => 'Netrokona Sadar'),
        );

        DB::table('upazilas')->insert($upazilas);
    }
}
